sources:
  - CustomDynamicFont/Sources
templates:
  - tools/sourcery/templates
output:
  CustomDynamicFontTests/Sources/Mocks/Sourcery 
args:
  autoMockableTestableImports:
    - CustomDynamicFont
  autoMockableImports:
    - RxSwift
    - RxCocoa
